server:
  port: 8080
  servlet:
    context-path: /api
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    username: postgres
    platform: postgres
    url: jdbc:postgresql://localhost:5432/dspesquisa
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      javax:
        persistence:
          schemaGeneration:
            createSource: metadata
            scriptsAction: create
            createTarget: create.sql
      hibernate:
        hbm2ddl:
          delimiter: ;
        format_sql: true