server:
  port: 8080
  servlet:
    context-path: /api
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true"
h2:
  console:
    enabled: true
    path: /h2-console
    settings:
      trace: false
      web-allow-others: false